
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://dotps1.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id

google-tracking-id: "UA-76976251-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Thomas Malkewitz"
title: "{ dotps1 }"
description: "Blog and website of Thomas Malkewitz @dotps1, blogging mainly for tech. Opinions expressed are my own."
keywords: "thomas, malkewitz, powershell, dotps1"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/favicon.ico"

background-img: "../img/intro-bg.png"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 2500
lines: # You can add HTML Tags in the Text
  - text: "Invoke-RestMethod -Uri https://api.github.com/users/dotps1"
  - text: "Find-Module -Repository PSGallery -Tag dotps1"
  - text: "Find-Script -Repository PSGallery -Tag dotps1"

# me-img: "/img/me.jpg"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

me-img: "https://github.com/dotps1.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: False

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: False
vkontakte-share: False

disqus-shortname: "dotps1"

syntax-highlight: True

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Just a beer drinking Github-er, automating daily tasks with PowerShell, or whatever.  And sometimes I go outside and ride my bike.  But mostly I just drink beer."
author_blurb_image: "/img/homercat.png"

##################
# Social Buttons #
##################

social:
  - title: "group"
    url: "https://grposh.github.io"
  - title: "github"
    url: "https://github.com/dotps1"
  - title: "terminal"
    url: "https://www.powershellgallery.com/profiles/dotps1"
  - title: "twitter"
    url: "https://twitter.com/dotps1"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/dotps1"
  - title: "windows"
    url: "https://social.technet.microsoft.com/profile/dotps1/"
  - title: "stack-overflow"
    url: https://stackoverflow.com/users/691551/dotps1
  - title: "steam"
    url: "https://steamcommunity.com/id/dotps1"
  - title: "twitch"
    url: "https://www.twitch.tv/dotps1"
  - title: "envelope"
    url: "mailto:thomas.malkewitz+dotps1@gmail.com"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/homercat.png"

##################
# GPG on Keybase #
##################

keybase-username: johnsmith
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Projects: 'projects'
  Blog: 'latest-post'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
